name: Run PHPCS and Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  test-php:
    name: Code Quality and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: mbstring, intl

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPCS
        run: composer lint

      - name: Run PHPUnit tests
        run: composer test

      - name: Push changes back (if needed)
        if: success()
        run: |
          git config user.name "roman1923"
          git config user.email "zhurakivskyy19@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "CI: auto-format and test passed"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/roman1923/user-directory-plugin.git
